### ISSUE TITLE
Issues after updating VM to PHP7.4

### ISSUE THREAD

**Issue by banderon** [Chassis/runkit7#2]
I've updated my `config.yaml` from `php: 7.3` to `php: 7.4`. This has resulted in errors that have prevented runkit7 from installing.

**OS:** macOS Catalina 10.15.4
**Vagrant:** 2.2.14
**Virtualbox:** 6.1.18
**config.yaml:**
```
# Chassis Configuration
#
# This file contains project-specific defaults that assume this repository
# has been cloned as the `content` directory of a Chassis virtual machine.
# For more information see http://docs.chassis.io/en/latest/config/

# Set the machine name
machine_name: tc.local

# Domain names to use for Vagrant
hosts:
  - local.tc.com

# Assign a static IP addresses on the private network. /etc/hosts must be updated.
ip: 10.12.34.56

# Configure SSH connection for SequelPro
ssh:
  port: 22

# Do not use multisite
multisite: No

# Extensions to install
extensions:
  - chassis/chassis_openssl
  - chassis/db_backup
  - chassis/gitignore
  - chassis/media_fallback
  - chassis/memcache
  - chassis/npm
  - chassis/phpini
  - chassis/phpmemcachedadmin
  - chassis/redirect_to_https
  - chassis/runkit7
  - chassis/sequelpro
  - chassis/tester
  - chassis/xdebug

# Configure ssl to keep the same cert/key
chassis_openssl:
  cert:
    replace: no
  key:
    replace: no

# Set the site name
site:
  name: Local Site

# Our theme
themes:
  - live-theme

# IDE for XDebug
# (Default is PHPSTORM; update if using a different IDE)
ide: PHPSTORM

# Database configuration
# (When overriding, include all values)
database:
  name: wordpress
  user: wordpress
  password: vagrantpassword
  prefix: wp_

# Must match .circleci/config.yml and wp-tests-config.php
tester_db:
  name: circle_test
  user: testuser
  password: password

# Configure VM's MySQL server to permit importing VIP database exports.
mysql:
  mysqld:
    sql_mode:
      - 'ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DATE,NO_ZERO_IN_DATE' 

# If a media file 404's within the VM, try production instead
media_fallback: 'https://tc.com/wp-content'

# Manually ignore certain untracked files which may exist in the Chassis root.
gitignore:
  - '*.key' # SSL key
  - 'backups' # live site content
  - 'chassis-backup.sql' # chassis/db_backup output

# PHP version
php: 7.4
```

Here is the erroring section of the provision output:
```
    tc.local: Notice: /Stage[main]/Runkit7/Package[php-xml]/ensure: created
    tc.local: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install 7.4-dev' returned 100: Reading package lists...
    tc.local: Building dependency tree...
    tc.local: Reading state information...
    tc.local: Some packages could not be installed. This may mean that you have
    tc.local: requested an impossible situation or if you are using the unstable
    tc.local: distribution that some required packages have not yet been created
    tc.local: or been moved out of Incoming.
    tc.local: The following information may help to resolve the situation:
    tc.local: 
    tc.local: The following packages have unmet dependencies:
    tc.local:  libghc-data-binary-ieee754-dev : Depends: libghc-base-dev-4.9.1.0-d28d6
    tc.local:                                   Depends: libghc-binary-dev-0.8.3.0-b46b7
    tc.local:                                   Conflicts: libghc-data-binary-ieee754-dev:i386 but 0.4.4-7build1 is to be installed
    tc.local:  libghc-data-binary-ieee754-dev:i386 : Depends: libghc-base-dev-4.9.1.0-5a696:i386
    tc.local:                                        Depends: libghc-binary-dev-0.8.3.0-93a7a:i386
    tc.local:                                        Conflicts: libghc-data-binary-ieee754-dev but 0.4.4-7build1 is to be installed
    tc.local:  libghc-ieee754-dev : Depends: libghc-base-dev-4.9.1.0-d28d6
    tc.local:                       Conflicts: libghc-ieee754-dev:i386 but 0.8.0-1 is to be installed
    tc.local:  libghc-ieee754-dev:i386 : Depends: libghc-base-dev-4.9.1.0-5a696:i386
    tc.local:                            Conflicts: libghc-ieee754-dev but 0.8.0-1 is to be installed
    tc.local: E: Unable to correct problems, you have held broken packages.
    tc.local: Error: /Stage[main]/Runkit7/Package[7.4-dev]/ensure: change from 'purged' to 'latest' failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install 7.4-dev' returned 100: Reading package lists...
    tc.local: Building dependency tree...
    tc.local: Reading state information...
    tc.local: Some packages could not be installed. This may mean that you have
    tc.local: requested an impossible situation or if you are using the unstable
    tc.local: distribution that some required packages have not yet been created
    tc.local: or been moved out of Incoming.
    tc.local: The following information may help to resolve the situation:
    tc.local: 
    tc.local: The following packages have unmet dependencies:
    tc.local:  libghc-data-binary-ieee754-dev : Depends: libghc-base-dev-4.9.1.0-d28d6
    tc.local:                                   Depends: libghc-binary-dev-0.8.3.0-b46b7
    tc.local:                                   Conflicts: libghc-data-binary-ieee754-dev:i386 but 0.4.4-7build1 is to be installed
    tc.local:  libghc-data-binary-ieee754-dev:i386 : Depends: libghc-base-dev-4.9.1.0-5a696:i386
    tc.local:                                        Depends: libghc-binary-dev-0.8.3.0-93a7a:i386
    tc.local:                                        Conflicts: libghc-data-binary-ieee754-dev but 0.4.4-7build1 is to be installed
    tc.local:  libghc-ieee754-dev : Depends: libghc-base-dev-4.9.1.0-d28d6
    tc.local:                       Conflicts: libghc-ieee754-dev:i386 but 0.8.0-1 is to be installed
    tc.local:  libghc-ieee754-dev:i386 : Depends: libghc-base-dev-4.9.1.0-5a696:i386
    tc.local:                            Conflicts: libghc-ieee754-dev but 0.8.0-1 is to be installed
    tc.local: E: Unable to correct problems, you have held broken packages.
    tc.local: Notice: /Stage[main]/Runkit7/Exec[install runkit7]: Dependency Package[7.4-dev] has failures: true
```
